create table if not exists public.products (
  id text primary key,
  name text not null,
  purchase_unit_price numeric(10,2) not null default 0,
  default_sale_price numeric(10,2) not null default 0,
  stock_quantity integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.boxes (
  id text primary key,
  name text not null,
  description text not null default '',
  image_url text not null default '/alien-box.jpeg',
  show_on_front_office boolean not null default false,
  sale_price numeric(10,2) not null default 0 check (sale_price >= 0),
  purchase_price numeric(10,2) check (purchase_price is null or purchase_price >= 0),
  weight_grams integer not null default 1 check (weight_grams > 0),
  has_variants boolean not null default false,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  created_at timestamptz not null default now()
);

alter table public.boxes
add column if not exists image_url text not null default '/alien-box.jpeg';

alter table public.boxes
add column if not exists sale_price numeric(10,2) not null default 0;

alter table public.boxes
add column if not exists purchase_price numeric(10,2);

alter table public.boxes
add column if not exists stock_quantity integer not null default 0;

alter table public.boxes
add column if not exists weight_grams integer not null default 1;

alter table public.boxes
add column if not exists has_variants boolean not null default false;

create table if not exists public.box_variants (
  id uuid primary key default gen_random_uuid(),
  box_id text not null references public.boxes(id) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  price numeric(10,2) not null check (price > 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists box_variants_box_id_idx
on public.box_variants(box_id, sort_order);

create table if not exists public.collections (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) > 0),
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.collection_boxes (
  collection_id uuid not null references public.collections(id) on delete cascade,
  box_id text not null references public.boxes(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (collection_id, box_id)
);

create index if not exists collection_boxes_box_id_idx
on public.collection_boxes(box_id);

create table if not exists public.shipping_rates (
  id bigint generated by default as identity primary key,
  carrier text not null check (carrier in ('mondial_relay', 'laposte')),
  delivery_mode text not null check (delivery_mode in ('pickup', 'home')),
  weight_min_grams integer not null check (weight_min_grams > 0),
  weight_max_grams integer not null check (weight_max_grams >= weight_min_grams),
  price numeric(10,2) not null check (price >= 0),
  created_at timestamptz not null default now(),
  unique (carrier, delivery_mode, weight_min_grams, weight_max_grams)
);

insert into public.shipping_rates
  (carrier, delivery_mode, weight_min_grams, weight_max_grams, price)
values
('mondial_relay','pickup',1,250,3.04),('mondial_relay','pickup',251,500,3.14),
('mondial_relay','pickup',501,1000,3.51),('mondial_relay','pickup',1001,2000,4.90),
('mondial_relay','pickup',2001,3000,5.21),('mondial_relay','pickup',3001,5000,5.21),
('mondial_relay','pickup',5001,7000,10.36),('mondial_relay','pickup',7001,10000,10.36),
('mondial_relay','pickup',10001,15000,16.16),('mondial_relay','pickup',15001,20000,16.26),
('mondial_relay','pickup',20001,30000,16.26),
('laposte','pickup',1,1000,4.50),('laposte','pickup',1001,3000,6.50),
('laposte','pickup',3001,10000,10.50),('laposte','pickup',10001,20000,17.50),
('mondial_relay','home',1,250,5.10),('mondial_relay','home',251,500,5.55),
('mondial_relay','home',501,1000,5.85),('mondial_relay','home',1001,2000,7.26),
('mondial_relay','home',2001,3000,8.54),('mondial_relay','home',3001,5000,10.25),
('mondial_relay','home',5001,7000,11.11),('mondial_relay','home',7001,10000,12.67),
('mondial_relay','home',10001,15000,12.57),('mondial_relay','home',15001,20000,20.45),
('mondial_relay','home',20001,30000,30.16),
('laposte','home',1,250,6.84),('laposte','home',251,500,7.71),
('laposte','home',501,750,8.60),('laposte','home',751,1000,9.34),
('laposte','home',1001,2000,10.48),('laposte','home',2001,3000,11.49),
('laposte','home',3001,4000,12.54),('laposte','home',4001,5000,13.54),
('laposte','home',5001,6000,14.17),('laposte','home',6001,7000,15.16),
('laposte','home',7001,8000,16.15),('laposte','home',8001,9000,17.17),
('laposte','home',9001,10000,18.17),('laposte','home',10001,11000,18.79),
('laposte','home',11001,12000,19.77),('laposte','home',12001,13000,20.74),
('laposte','home',13001,14000,21.75),('laposte','home',14001,15000,22.73),
('laposte','home',15001,16000,23.70),('laposte','home',16001,17000,24.68),
('laposte','home',17001,18000,25.66),('laposte','home',18001,19000,26.65),
('laposte','home',19001,20000,27.62),('laposte','home',20001,21000,28.33),
('laposte','home',21001,22000,29.29),('laposte','home',22001,23000,30.28),
('laposte','home',23001,24000,31.25),('laposte','home',24001,25000,32.19),
('laposte','home',25001,26000,33.19),('laposte','home',26001,27000,34.13),
('laposte','home',27001,28000,35.11),('laposte','home',28001,29000,36.12),
('laposte','home',29001,30000,37.05)
on conflict (carrier, delivery_mode, weight_min_grams, weight_max_grams)
do update set price = excluded.price;

create table if not exists public.box_images (
  id text primary key,
  box_id text not null references public.boxes(id) on delete cascade,
  image_url text not null,
  storage_path text not null,
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now()
);

create index if not exists box_images_box_id_sort_order_idx
on public.box_images(box_id, sort_order);

create table if not exists public.box_complete_images (
  id text primary key,
  box_id text not null references public.boxes(id) on delete cascade,
  image_url text not null,
  storage_path text not null,
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now()
);

create index if not exists box_complete_images_box_id_sort_order_idx
on public.box_complete_images(box_id, sort_order);

create table if not exists public.box_items (
  box_id text not null references public.boxes(id) on delete cascade,
  product_id text not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  sale_price numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  primary key (box_id, product_id)
);

-- Conserve le prix actuel lors de la première migration, puis la colonne
-- boxes.sale_price devient l'unique source de vérité.
update public.boxes as box
set sale_price = totals.sale_price
from (
  select box_id, sum(sale_price * quantity) as sale_price
  from public.box_items
  group by box_id
) as totals
where box.id = totals.box_id
  and box.sale_price = 0;

create table if not exists public.events (
  id text primary key,
  title text not null,
  description text not null default '',
  event_date date,
  location text not null default '',
  show_on_front_office boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  stripe_session_id text unique,
  status text not null default 'pending_payment'
    check (status in ('pending_payment', 'paid', 'preparing', 'shipped', 'delivered', 'cancelled')),
  customer_first_name text not null,
  customer_last_name text not null,
  customer_email text not null,
  customer_phone text,
  delivery_method text not null
    check (delivery_method in ('mondial_relay_pickup', 'laposte_pickup', 'mondial_relay_home', 'laposte_home')),
  delivery_carrier text not null,
  delivery_mode text not null check (delivery_mode in ('pickup', 'home')),
  delivery_price numeric(10,2) not null check (delivery_price >= 0),
  delivery_address text,
  delivery_postal_code text,
  delivery_city text,
  relay_point jsonb,
  items jsonb not null,
  items_total numeric(10,2) not null check (items_total >= 0),
  total_weight_grams integer not null default 1 check (total_weight_grams > 0),
  total numeric(10,2) not null check (total >= 0),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_status_idx on public.orders(status);

alter table public.orders
add column if not exists total_weight_grams integer not null default 1;

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text,
  email text not null,
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(comment) between 1 and 500),
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reviews_created_at_idx on public.reviews(created_at desc);
create index if not exists reviews_is_published_idx on public.reviews(is_published);

create or replace view public.public_reviews
with (security_invoker = false)
as
select id, first_name, last_name, rating, comment, created_at
from public.reviews
where is_published = true;

revoke all on public.reviews from anon;
grant select, update on public.reviews to authenticated;
grant select on public.public_reviews to anon, authenticated;

alter table public.events
alter column event_date drop not null;

alter table public.products enable row level security;
alter table public.shipping_rates enable row level security;
alter table public.boxes enable row level security;
alter table public.box_images enable row level security;
alter table public.box_complete_images enable row level security;
alter table public.box_items enable row level security;
alter table public.box_variants enable row level security;
alter table public.collections enable row level security;
alter table public.collection_boxes enable row level security;
alter table public.events enable row level security;
alter table public.orders enable row level security;
alter table public.reviews enable row level security;

insert into storage.buckets (id, name, public)
values ('box-images', 'box-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "products_select_public" on public.products;
create policy "products_select_public"
on public.products
for select
to anon, authenticated
using (true);

drop policy if exists "products_write_authenticated" on public.products;
create policy "products_write_authenticated"
on public.products
for all
to authenticated
using (true)
with check (true);

drop policy if exists "boxes_select_public" on public.boxes;
create policy "boxes_select_public"
on public.boxes
for select
to anon, authenticated
using (true);

drop policy if exists "boxes_write_authenticated" on public.boxes;
create policy "boxes_write_authenticated"
on public.boxes
for all
to authenticated
using (true)
with check (true);

drop policy if exists "box_images_select_public" on public.box_images;
create policy "box_images_select_public"
on public.box_images
for select
to anon, authenticated
using (true);

drop policy if exists "shipping_rates_select_public" on public.shipping_rates;
create policy "shipping_rates_select_public"
on public.shipping_rates for select to anon, authenticated using (true);

drop policy if exists "box_images_write_authenticated" on public.box_images;
create policy "box_images_write_authenticated"
on public.box_images
for all
to authenticated
using (true)
with check (true);

drop policy if exists "box_complete_images_select_public" on public.box_complete_images;
create policy "box_complete_images_select_public"
on public.box_complete_images
for select
to anon, authenticated
using (true);

drop policy if exists "box_complete_images_write_authenticated" on public.box_complete_images;
create policy "box_complete_images_write_authenticated"
on public.box_complete_images
for all
to authenticated
using (true)
with check (true);

drop policy if exists "box_items_select_public" on public.box_items;
create policy "box_items_select_public"
on public.box_items
for select
to anon, authenticated
using (true);

drop policy if exists "box_variants_select_public" on public.box_variants;
create policy "box_variants_select_public"
on public.box_variants for select to anon, authenticated using (true);

drop policy if exists "box_variants_write_authenticated" on public.box_variants;
create policy "box_variants_write_authenticated"
on public.box_variants for all to authenticated using (true) with check (true);

drop policy if exists "collections_select_public" on public.collections;
create policy "collections_select_public"
on public.collections for select to anon, authenticated using (true);

drop policy if exists "collections_write_authenticated" on public.collections;
create policy "collections_write_authenticated"
on public.collections for all to authenticated using (true) with check (true);

drop policy if exists "collection_boxes_select_public" on public.collection_boxes;
create policy "collection_boxes_select_public"
on public.collection_boxes for select to anon, authenticated using (true);

drop policy if exists "collection_boxes_write_authenticated" on public.collection_boxes;
create policy "collection_boxes_write_authenticated"
on public.collection_boxes for all to authenticated using (true) with check (true);

drop policy if exists "box_items_write_authenticated" on public.box_items;
create policy "box_items_write_authenticated"
on public.box_items
for all
to authenticated
using (true)
with check (true);

drop policy if exists "events_select_public" on public.events;
create policy "events_select_public"
on public.events
for select
to anon, authenticated
using (true);

drop policy if exists "events_write_authenticated" on public.events;
create policy "events_write_authenticated"
on public.events
for all
to authenticated
using (true)
with check (true);

drop policy if exists "orders_select_authenticated" on public.orders;
create policy "orders_select_authenticated"
on public.orders for select to authenticated using (true);

drop policy if exists "orders_update_authenticated" on public.orders;
create policy "orders_update_authenticated"
on public.orders for update to authenticated using (true) with check (true);

drop policy if exists "reviews_select_authenticated" on public.reviews;
create policy "reviews_select_authenticated"
on public.reviews for select to authenticated using (true);

drop policy if exists "reviews_update_authenticated" on public.reviews;
create policy "reviews_update_authenticated"
on public.reviews for update to authenticated using (true) with check (true);

drop policy if exists "box_images_storage_select_public" on storage.objects;
create policy "box_images_storage_select_public"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'box-images');

drop policy if exists "box_images_storage_insert_authenticated" on storage.objects;
create policy "box_images_storage_insert_authenticated"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'box-images');

drop policy if exists "box_images_storage_update_authenticated" on storage.objects;
create policy "box_images_storage_update_authenticated"
on storage.objects
for update
to authenticated
using (bucket_id = 'box-images')
with check (bucket_id = 'box-images');

drop policy if exists "box_images_storage_delete_authenticated" on storage.objects;
create policy "box_images_storage_delete_authenticated"
on storage.objects
for delete
to authenticated
using (bucket_id = 'box-images');
